In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # List of numbers
numbersGroup = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # List of "list of numbers"

In [4]:
print(numbers[0])

1


In [5]:
print(numbersGroup)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [6]:
zeros = np.zeros(5)  # Array of 5 zeros
print("Zeros array:", zeros)

Zeros array: [0. 0. 0. 0. 0.]


In [7]:
ones = np.ones((3, 3))  # 3x3 matrix of ones
print("Ones matrix:")
print(ones)

Ones matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# Random numbers
random_array = np.random.rand(20)  # 5 random numbers between 0 and 1
print("Random array:", random_array)

Random array: [0.84085608 0.02629976 0.16428392 0.7764956  0.85131284 0.64879759
 0.89204489 0.34167329 0.96080862 0.09375461 0.41974232 0.46967654
 0.89718783 0.59994198 0.46950179 0.8481258  0.314799   0.18065583
 0.68429126 0.37919114]


In [9]:
# Range of values
range_array = np.arange(0, 100, 4)  # Start, stop, step
print("Range array:", range_array)

Range array: [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]
