In [3]:
import numpy as np

In [7]:
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # List of numbers
numbersGroup = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # List of "list of numbers"

In [10]:
print(numbers[0])

1


In [26]:
print(numbersGroup)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [19]:
zeros = np.zeros(5)  # Array of 5 zeros
print("Zeros array:", zeros)

Zeros array: [0. 0. 0. 0. 0.]


In [25]:
ones = np.ones((3, 3))  # 3x3 matrix of ones
print("Ones matrix:")
print(ones)

Ones matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# Random numbers
random_array = np.random.rand(20)  # 5 random numbers between 0 and 1
print("Random array:", random_array)

Random array: [0.38816667 0.28873808 0.22315047 0.09033415 0.70688575 0.18436924
 0.706098   0.63437141 0.27173252 0.83442649 0.72198657 0.78686022
 0.5926163  0.47859392 0.17877275 0.05705542 0.05783318 0.16931988
 0.7659077  0.40359635]


In [40]:
# Range of values
range_array = np.arange(0, 100, 4)  # Start, stop, step
print("Range array:", range_array)

Range array: [ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]
